### ISSUE TITLE
create a hydro version that compiles with gcc-4.8

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/CMP2020M#1]
currently it doesn't compile on hydro, see https://lcas.lincoln.ac.uk/jenkins/job/ros-hydro-catkinized-downward_binarydeb_precise_amd64/1/console failing with `cc1plus: error: unrecognized command line option '-std=c++11'`

So, we need to create a hydro-devel branch, make gcc-4.8 a dependency and change `CXX=g++-4.8` in the `Makefile`. At least that's my first shot.

**Comment by marc-hanheide** [comment]
@cdondrup I wanted to make you aware of this: We have an ubuntu package `catkinized_downward` for indigo already on the server, but the hydro version still fails, due to this problem.

**Comment by cdondrup** [comment]
I'll have a look.

**Comment by marc-hanheide** [comment]
Don't! I'm on it! I just wanted to let you know that there's no hydro yet. I think I found a solution: 34887451416b1f1f5055f9a0133c5a4726a30d88

**Comment by marc-hanheide** [comment]
The more promising solution is to revert to a version of downward that compiled with earlier gcc version. There are no other recent changes than that.

**Comment by cdondrup** [comment]
Have to fix my fathers PC first anyway... The joys of being at home ;)
Just from experience, GCC 4.8 is not available from the standard repos and needs a separate private ppa. But that works fine. Can lookup the way I installed it for the winter school but I guess custom ppas are not really desirable.

**Comment by marc-hanheide** [comment]
My solution works without g++-4.8. All is good.

**Comment by marc-hanheide** [comment]
built and released
